# -*- coding: utf-8 -*-
"""Neural_Networks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZSZpiyj9UPigfuFBVmbS6OrWEya5-V6M
"""

import sys
import numpy as np
import matplotlib

print("Python: ", sys.version)
print("Numpy: ", np.__version__)
print("Matplotlib: ", matplotlib.__version__)

#Coding a simple neuron that has inputs, weights, bias
inputs = [1.0, 2.0, 3.0, 2.5]

#Modelling 3 neurons with 3 weights and bias
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_output = []
for weight_list, single_bias in zip(weights, biases):
  current_output = 0
  for indiv_weights, n_input in zip(weight_list, inputs):
    current_output += indiv_weights * n_input
  current_output += single_bias
  layer_output.append(current_output)

